### ISSUE TITLE
Missing packages for DNS

### ISSUE THREAD

**Issue by sgallagher** [modularity-modules/freeipa#2]
The `freeipa-server-dns` package requires the `bind-dyndb-ldap` and `python2-dns` packages, which are not provided by either the freeipa module or any of the runtime dependencies that have been specified.

**Comment by nphilipp** [comment]
* `bind-dyndb-ldap` would be built as part of the `freeipa` module itself, but [the latest build failed]( https://mbs.fedoraproject.org/module-build-service/1/module-builds/1226) ("Failed to build artifact freeipa in Koji"), i.e. this should be fixed as soon as whatever breaks the build is fixed.
* `python2-dns` is built from `python-dns` which is built in the `python3-ecosystem` module (where py2k pkgs are filtered out) but not in `python2-ecosystem`. I think this is the most sensible place to put it and let `freeipa` require it as a runtime dependency.

(ping @asamalik, @KarstenHopp, @ncoghlan)

**Comment by sgallagher** [comment]
I just built the master branch of the freeipa module successfully, which included `bind-dyndb-ldap`. I'd prefer to have @ncoghlan or someone else on the Python team sort out what `python-dns` needs here.

**Comment by ncoghlan** [comment]
python2-dns has been added to python2-ecosystem now: https://src.fedoraproject.org/modules/python2-ecosystem/c/14e61918f1f23161a2ce15153e2892480f850d8f?branch=master

**Comment by alexxa** [comment]
@sgallagher @nphilipp @ncoghlan Can we close this ticket as resolved?

**Comment by sgallagher** [comment]
@alexxa Let's wait until we have a successful compose with these packages, because we can't currently test it to verify that the change was successful and sufficient. It should be testable once the [compose that is currently running](https://kojipkgs.fedoraproject.org/compose/Fedora-Modular-27-20171031.n.1/) is completed.

**Comment by nphilipp** [comment]
@sgallagher I assume we have a compose containing freeipa meanwhile and close this, right?

**Comment by sgallagher** [comment]
Yes, we're good now.
